name: Add Approved Submission

on:
  issues:
    types: [closed]

jobs:
  add-location:
    if: contains(github.event.issue.labels.*.name, 'approved')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Parse Issue & Append to GeoJSON
        run: |
          node .github/scripts/parse-issue.js "${{ github.event.issue.body }}"

      - name: Commit and Push
        run: |
          git config user.name "urbexbot"
          git config user.email "actions@github.com"
          git add locations.geojson
          git commit -m "Add location from issue #${{ github.event.issue.number }}"
          git push
